php:
  preset: laravel
  disabled:
    - unused_use
  finder:
    not-name:
      - index.php
      - server.php
      - deploy.php
      - .env.prod
    not-path:
      - "Themes/Adminlte/assets/vendor/*"
#js:
#  finder:
#    not-name:
#      - webpack.mix.js
#css: true
