version: '2.1'
services:
  app:
    build:
      context: ./docker/app
    image: asgardcms/app:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html:cached
    networks:
      - digiqrp_net
  #redis:
  #  build:
  #    context: ./docker/redis
  #  image: asgardcms/redis:latest
  #  volumes:
  #    - redisdata:/data
  #  ports:
  #    - "6379:6379"
  #  networks:
  #    - digiqrp_net

  mysql:
    build:
      context: ./docker/mysql
    image: asgardcms/mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digiqrp
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - ./docker/db:/var/lib/mysql
    networks:
      - digiqrp_net

  node:
    build:
      context: ./docker/node
    image: asgardcms/node:latest
    volumes:
      - .:/var/www/html

  #blackfire:
  #  image: blackfire/blackfire
  #  environment:
  #    BLACKFIRE_SERVER_ID:
  #    BLACKFIRE_SERVER_TOKEN:
  #  networks:
  #  - digiqrp_net

  mailhog:
    image: mailhog/mailhog:latest
    container_name: myapp-mailhog
    ports:
      - "8003:1025"
      - "8100:8025"

volumes:
  #redisdata:
  #  driver: local
  mysqldata:
    driver: local

networks:
  digiqrp_net:
    driver: bridge
